package com.eteach.eteach.enums;

public enum Grade {
    FIRST_PRIMARY,
    SECOND_PRIMARY,
    THIRD_PRIMARY,
    FOURTH_PRIMARY,
    FIFTH_PRIMARY,
    SIXTH_PRIMARY,
    FIRST_PREPARATORY,
    SECOND_PREPARATORY,
    THIRD_PREPARATORY,
    FIRST_SECONDARY,
    SECOND_SECONDARY,
    THIRD_SECONDARY,
}
